const userLogin="/user/login";
const userRegister="/user/register";
const userGet="/user/get";
const loginUrl="./routes/login";
const registerUrl="./routes/register";
const getUrl="./routes/user";
const userDelete="/user/delete";
const deleteUrl="./routes/delete";
module.exports={userLogin,userRegister,userGet,loginUrl,registerUrl,getUrl,userDelete,deleteUrl}